### ISSUE TITLE
Crear vista de Nosotros - frontend

### ISSUE THREAD

**Issue by DiegoCuadros** [AnderMendoza/Ecommerce-Template#106]
Reutilizar el header y footer

Se tiene que respetar la paleta de colores que manejamos hasta el momento

Contar con texto referente a nosotros como empresa

Adaptarlo a las demás vistas

**Comment by AnderMendoza** [comment]
Recuerda que ya puedes crear también un PR en **modo Draft** para poder ver los cambios que subas en tiempo real con el servicio de Vercel.
Quedo atento a tus avances. 😁

**Comment by DiegoCuadros** [comment]
Avance de pagina de nosotros.
Agregado titulo y como referencia un texto.
Imagen de Fondo con Opacidad agregado.
Pagina Nosotros conectada con las demas.

**Comment by AnderMendoza** [comment]
### OJO 👀
No dejes de lado la funcionalidad de los botones en el modo responsive, los siguientes botones han perdido funcionalidad. Puedes revisar los errores que te arroja la consola de tu navegador para que los puedas solucionar. 

![Captura de pantalla 2022-11-04 202442](https://user-images.githubusercontent.com/80181518/200094948-48bd74f3-92a8-43d3-9302-866e1b968139.png)

¡Sé que lo resolverás! 🙌
