### ISSUE TITLE
Planificacion de un login, CRUD y API - frontend & backend & testing

### ISSUE THREAD

**Issue by AnderMendoza** [AnderMendoza/Ecommerce-Template#92]
Compartir todos los recursos que encuentren referente a la realizacion de esta tarea con Java y MySQL

**Comment by pedropablosalas** [comment]
Encontre un video que nos podria servir para la creacion de la pestaña de login junto a una de registro 
Aqui les mando espero q les sea util [https://www.youtube.com/watch?v=NLpK2W1TM2A&ab_channel=PuritoCodigo](url)

**Comment by Jankarurosu** [comment]
Lista de videos para crear un login y registro usando PHP y MySQL:

https://www.youtube.com/watch?v=c3GoigQ5vRE&list=PLAFTVct4TDOa1HHObYNcGqRXsYTcCnfF4&ab_channel=MagtimusPro
